### ISSUE TITLE
[Bug]: An error occurred while training the crew (litellm.BadRequestError)

### ISSUE THREAD

**Issue by bmacer** [AgentOps-AI/AgentStack#123]
### Contact Details

bobbysox322@gmail.com

### 📦 Package Version

0.2.2.1

### 🔎 Describe the Bug

Setting up a simple hello world proof-of-concept.

Agent:
```
sayHello:
  role: >-
    just say hello
  goal: >-
    just say hello
  backstory: >-
    Add your backstory here
  llm: xai/grok-beta
```

Tasks:
```
sayHi:
  description: >-
    just say hi
  expected_output: >-
    just say hi
  agent: sayHello
```

crew.py
```
from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
import tools

@CrewBase
class Dec11Crew():
    """dec11 crew"""

    @agent
    def sayHello(self) -> Agent:
        return Agent(
            config=self.agents_config['sayHello'],
            tools=[], # add tools here or use `agentstack tools add <tool_name>
            verbose=True,
        )

    @task
    def sayHi(self) -> Task:
        return Task(
            config=self.tasks_config['sayHi'],
        )

    @crew
    def crew(self) -> Crew:
        """Creates the Test crew"""
        return Crew(
            agents=self.agents, # Automatically created by the @agent decorator
            tasks=self.tasks, # Automatically created by the @task decorator
            process=Process.sequential,
            verbose=True,
            # process=Process.hierarchical, # In case you wanna use that instead https://docs.crewai.com/how-to/Hierarchical/
        )
```

When I run `agentstack run` I get an error:
```
File "src/main.py", line 28
    raise Exception(f"An error occurred while training the crew: {e}")
SyntaxError: invalid syntax
```

Seems to indicate it's HuggingFace-related when I run `py src/main`
```
Provider List: https://docs.litellm.ai/docs/providers
ERROR:root:Failed to get supported params: argument of type 'NoneType' is not iterable
# Agent: just say hello
## Task: just say hi
```

When I go to https://docs.litellm.ai/docs/providers, it looks like `xai/grok-beta` is a valid LLM, but maybe I did something wrong?

Full traceback:
```
Traceback (most recent call last):
  File "/Users/bmacer/Desktop/home/agentstack/dec11/src/main.py", line 60, in <module>
    run()
  File "/Users/bmacer/Desktop/home/agentstack/dec11/src/main.py", line 19, in run
    Dec11Crew().crew().kickoff(inputs=inputs)
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/crew.py", line 553, in kickoff
    result = self._run_sequential_process()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/crew.py", line 660, in _run_sequential_process
    return self._execute_tasks(self.tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/crew.py", line 758, in _execute_tasks
    task_output = task.execute_sync(
                  ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/task.py", line 192, in execute_sync
    return self._execute_core(agent, context, tools)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/task.py", line 250, in _execute_core
    result = agent.execute_task(
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agent.py", line 357, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agent.py", line 357, in execute_task
    result = self.execute_task(task, context, tools)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agent.py", line 356, in execute_task
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agent.py", line 345, in execute_task
    result = self.agent_executor.invoke(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 102, in invoke
    formatted_answer = self._invoke_loop()
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 193, in _invoke_loop
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/agents/crew_agent_executor.py", line 115, in _invoke_loop
    answer = self.llm.call(
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/crewai/llm.py", line 164, in call
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/agentops/llms/providers/litellm.py", line 195, in patched_function
    result = self.original_create(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 1006, in wrapper
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 896, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 3009, in completion
    raise exception_type(
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 906, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(
                                                            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 313, in get_llm_provider
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 290, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=xai/grok-beta
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
```

### 🤝 Contribution

- [ ] Yes, I'd be happy to submit a pull request with these changes.
- [ ] I need some guidance on how to contribute.
- [X] I'd prefer the AgentStack team to handle this update.

**Comment by bmacer** [comment]
It looks like an issue with `litellm` version.
The issue can be reproduced with version `1.50.2`, but is fixed in `1.54.1`.

**Comment by bmacer** [comment]
I think this can be closed, I don't know how I got into this broken state, but starting fresh again, all seems good.
